FROM python:3.12-alpine
ARG VERSION
ARG VCS_REF
ARG VCS_URL
LABEL org.opencontainers.image.source="${VCS_URL}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.version="${VERSION}"
RUN apk add --no-cache coreutils \
    && pip install --no-cache-dir pycdlib
WORKDIR /app
COPY script.py /app/mkiso
ENTRYPOINT ["python", "/app/mkiso"]
